language: perl

perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"

install:
    - cpanm parent PPI Sub::Identify Test::Builder::Module Module::Build Module::Build::Pluggable Test::More Test::Builder::Tester

script:
    - perl Build.PL
    - ./Build test
